#! /bin/sh
bspc monitor HDMI-0 -d one
bspc monitor %DP-2.8 -d two three four five six seven eight nine ten
bspc config top_padding        5
bspc config bottom_padding     40
bspc config left_padding       5
bspc config right_padding      5
bspc config border_width         3
bspc config window_gap          20
bspc config normal_border_color "#42423d"
bspc config focused_border_color "#8e8585"
#bspc config focused_border_color "#eee4e5"
#bspc config presel_border_color "#ffbec9"
bspc config split_ratio          0.52
bspc config focus_follows_pointer true

bspc rule -a mpv state=floating
bspc rule -a "*:sxiv" state=floating
bspc rule -a URxvt:stick state=floating sticky=on center
bspc rule -a URxvt:stick1 state=floating sticky=on
bspc rule -a URxvt:stick2 state=floating sticky=on
bspc rule -a URxvt:float state=floating
bspc rule -a Steam:"Friends List" state=floating
#bspc rule -a "polybar" layer=above

bspc rule -a plexmediaplayer desktop='one'
bspc rule -a Spotify desktop='four'

xsetroot -cursor_name left_ptr&
#wicd-gtk -t
